#include <stdlib.h>
#include <iostream>
#include <fstream>


using namespace std;

int main()
{
    int HB0=0;
    int HB1=0;
    int HB2=0;
    int SB0=0;
    int SB1=0;
    int SB2=0;
    int SB3=0;
    int SB4=0;
    int SB5=0;
    int SB6=0;
    int PB0=0;
    int PB1=0;
    int PB2=0;
    int PB3=0;
    int PB4=0;
    int PB5=0;
    int PB6=0;
    int PB7=0;
    int PB8=0;
    int PB9=0;
    int PB10=0;
    int PB11=0;
    int PB12=0;
    int PB13=0;
    int PB14=0;
    int PB15=0;
    int PB16=0;
    int PB17=0;
    int PB18=0;
    int PB19=0;
    int PB20=0;
    int PB21=0;
    int PB22=0;
    int PB23=0;
    int PB24=0;
    int PB25=0;
    int PB26=0;
    int PB27=0;

 cout<<"HB0 = ";
 cin>>HB0;
 cout<<"HB1 = ";
 cin>>HB1;
 cout<<"HB2 = ";
 cin>>HB2;
 cout<<"SB0 = ";
 cin>>SB0;
 cout<<"SB1 = ";
 cin>>SB1;
 cout<<"SB2 = ";
 cin>>SB2;
 cout<<"SB3 = ";
 cin>>SB3;
 cout<<"SB4 = ";
 cin>>SB4;
 cout<<"SB5 = ";
 cin>>SB5;
 cout<<"SB6 = ";
 cin>>SB6;
 cout<<"PB0 = ";
 cin>>PB0;
 cout<<"PB1 = ";
 cin>>PB1;
 cout<<"PB2 = ";
 cin>>PB2;
 cout<<"PB3 = ";
 cin>>PB3;
 cout<<"PB4 = ";
 cin>>PB4;
 cout<<"PB5 = ";
 cin>>PB5;
 cout<<"PB6 = ";
 cin>>PB6;
 cout<<"PB7 = ";
 cin>>PB7;
 cout<<"PB8 = ";
 cin>>PB8;
 cout<<"PB9 = ";
 cin>>PB9;
 cout<<"PB10 = ";
 cin>>PB10;
 cout<<"PB11 = ";
 cin>>PB11;
 cout<<"PB12 = ";
 cin>>PB12;
 cout<<"PB13 = ";
 cin>>PB13;
 cout<<"PB14 = ";
 cin>>PB14;
 cout<<"PB15 = ";
 cin>>PB15;
 cout<<"PB16 = ";
 cin>>PB16;
 cout<<"PB17 = ";
 cin>>PB17;
 cout<<"PB18 = ";
 cin>>PB18;
 cout<<"PB19 = ";
 cin>>PB19;
 cout<<"PB20 = ";
 cin>>PB20;
 cout<<"PB21 = ";
 cin>>PB21;
 cout<<"PB22 = ";
 cin>>PB22;
 cout<<"PB23 = ";
 cin>>PB23;
 cout<<"PB24 = ";
 cin>>PB24;
 cout<<"PB25 = ";
 cin>>PB25;
 cout<<"PB26 = ";
 cin>>PB26;
 cout<<"PB27 = ";
 cin>>PB27;

 ofstream out("E:\\test_files\\parser1.txt",ios::binary|ios::out);
   out.write((char*)&HB0,sizeof HB0);
   out.write((char*)&HB1,sizeof HB1);
   out.write((char*)&HB2,sizeof HB2);
   out.write((char*)&SB0,sizeof SB0);
   out.write((char*)&SB1,sizeof SB1);
   out.write((char*)&SB2,sizeof SB2);
   out.write((char*)&SB3,sizeof SB3);
   out.write((char*)&SB4,sizeof SB4);
   out.write((char*)&SB5,sizeof SB5);
   out.write((char*)&SB6,sizeof SB6);
   out.write((char*)&PB0,sizeof PB0);
   out.write((char*)&PB1,sizeof PB1);
   out.write((char*)&PB2,sizeof PB2);
   out.write((char*)&PB3,sizeof PB3);
   out.write((char*)&PB4,sizeof PB4);
   out.write((char*)&PB5,sizeof PB5);
   out.write((char*)&PB6,sizeof PB6);
   out.write((char*)&PB7,sizeof PB7);
   out.write((char*)&PB8,sizeof PB8);
   out.write((char*)&PB9,sizeof PB9);
   out.write((char*)&PB10,sizeof PB10);
   out.write((char*)&PB11,sizeof PB11);
   out.write((char*)&PB12,sizeof PB12);
   out.write((char*)&PB13,sizeof PB13);
   out.write((char*)&PB14,sizeof PB14);
   out.write((char*)&PB15,sizeof PB15);
   out.write((char*)&PB16,sizeof PB16);
   out.write((char*)&PB17,sizeof PB17);
   out.write((char*)&PB18,sizeof PB18);
   out.write((char*)&PB19,sizeof PB19);
   out.write((char*)&PB20,sizeof PB20);
   out.write((char*)&PB21,sizeof PB21);
   out.write((char*)&PB22,sizeof PB22);
   out.write((char*)&PB23,sizeof PB23);
   out.write((char*)&PB24,sizeof PB24);
   out.write((char*)&PB25,sizeof PB25);
   out.write((char*)&PB26,sizeof PB26);
   out.write((char*)&PB27,sizeof PB27);
 out.close();

 return(0);
}
